apiVersion: v1
kind: Service
metadata:
  name: admin-staff-service-svc
  namespace: distrischool
spec:
  selector:
    app: admin-staff-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
