apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: distrischool
type: Opaque
stringData:
  # For postgres container
  username: "admin"
  password: "admin"
  # For Spring Boot services (envFrom will map these directly)
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "admin"
