apiVersion: v1
kind: Service
metadata:
  name: teacher-service-svc
  namespace: distrischool
spec:
  selector:
    app: teacher-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
